typography_spectrum: 0.20326
color:
  brandColors:
    - '#ff6600'
    - '#ffffff'
    - '#ff8c40'
    - '#ffd9c0'
    - '#ffc39c'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.4375
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: vandalcleaning
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: vandal.cleaning
description: Graffiti Reinigung
purpose: []
